export const jacketList = [
    {name: "Float Coat",
     price: 2999,
     img: "RainyDays_Jacket1.png",
     description: "A thick orange, black and silver raincoat"},
    {name: "Storm jacket",
     price: 990,
     img: "RainyDays_Jacket6.png",
     description: "Black winter jacket with grey details."},
    {name: "Scott's windproof jacket",
     price: 1000,
     img: "RainyDays_Jacket2.png",
     description: "Grey windproof jacket."},
    {name: "Mens windproof ski jacket",
     price: 1500,
     img: "RainyDays_Jacket3.png",
     description: "Red ski jacket with black details."},
    {name: "Scott's Snowmobile jacket",
     price: 3599,
     img: "RainyDays_Jacket4.png",
     description: "Black winter jacket with white details."},
    {name: "Monsun jacket",
     price: 500,
     img: "RainyDays_Jacket5.png",
     description: "Grey allround biker jacket."},
    {name: "Patagonia Fleece Jacket",
     price: 999,
     img: "RainyDays_Jacket7.png",
     description:"Olive colored cosy fleece."}
]