export const jacketList = [
    {name: "Float Coat",
     price: 2999,
     img: "RainyDays_Jacket1.png",
     description: "A thick orange, black and silver raincoat"},
    {name: "Storm jacket",
     price: 990,
     img: "RainyDays_Jacket6.png",
     description: "Black winter jacket with grey details."},
    {name: "Scott's windproof jacket",
     price: 1000,
     img: "RainyDays_Jacket2.png",
     description: "Grey windproof jacket."},
    {name: "Mens windproof ski jacket",
     price: 1500,
     img: "RainyDays_Jacket3.png",
     description: "Red ski jacket with black details."},
    {name: "Scott's Snowmobile jacket",
     price: 3599,
     img: "RainyDays_Jacket4.png",
     description: "Black winter jacket with white details."},
    {name: "Monsun jacket",
     price: 500,
     img: "RainyDays_Jacket5.png",
     description: "Grey allround biker jacket."},
    {name: "Patagonia Fleece Jacket",
     price: 999,
     img: "RainyDays_Jacket7.png",
     description:"Olive colored cosy fleece."}
]


// export const jacketList = [
//     {name: "Float Coat",
//      price: 2999,
//      img: "RainyDays_Jacket1.png",
//      description: "A thick orange, black and silver raincoat",
//      color: ["red", "blue", "yellow", "black", "orange"],
//      size: ["xs", "s", "m", "l", "xl"]},
//     {name: "Storm jacket",
//      price: 990,
//      img: "RainyDays_Jacket6.png",
//      description: "Black winter jacket with grey details.",
//      color: ["red", "blue", "yellow", "black", "orange"]},
//     {name: "Scott's windproof jacket",
//      price: 1000,
//      img: "RainyDays_Jacket2.png",
//      description: "Grey windproof jacket.",
//      color: ["red", "blue", "yellow", "black", "orange"]},
//     {name: "Mens windproof ski jacket",
//      price: 1500,
//      img: "RainyDays_Jacket3.png",
//      description: "Red ski jacket with black details.",
//      color: ["red", "blue", "yellow", "black", "orange"]},
//     {name: "Scott's Snowmobile jacket",
//      price: 3599,
//      img: "RainyDays_Jacket4.png",
//      description: "Black winter jacket with white details.",
//      color: ["red", "blue", "yellow", "black", "orange"]},
//     {name: "Monsun jacket",
//      price: 500,
//      img: "RainyDays_Jacket5.png",
//      description: "Grey allround biker jacket.",
//      color: ["red", "blue", "yellow", "black", "orange"]},
//     {name: "Patagonia Fleece Jacket",
//      price: 999,
//      img: "RainyDays_Jacket7.png",
//      description:"Olive colored cosy fleece.",
//      color: ["red", "blue", "yellow", "black", "orange"]}
// ]

/*
const products = [
    {name: "Float Coat",
     price: 2999,
     img: src="images/product_img/RainyDays_Jacket1.png"},
    {name: "Storm jacket",
     price: 990,
     img: src="images/product_img/RainyDays_Jacket6.png"},
    {name: "Scott's windproof jacket",
     price: 1000,
     img: src="images/product_img/RainyDays_Jacket2.png"},
    {name: "Mens windproof ski jacket",
     price: 1500,
     img: src="images/product_img/RainyDays_Jacket3.png"},
    {name: "Scott's Snowmobile jacket",
     price: 3599,
     img: src="images/product_img/RainyDays_Jacket4.png"},
    {name: "Monsun jacket",
     price: 500,
     img: src="images/product_img/RainyDays_Jacket5.png"},
    {name: "Patagonia Fleece Jacket",
     price: 999,
     img: src="images/product_img/RainyDays_Jacket7.png"}
]
*/

